### ISSUE TITLE
Personhood and dynamic personalities

### ISSUE THREAD

**Issue by tdimino** [opensouls/SocialAGI#10]
@kafischer Thank you for initiating this project, and laying a foundation which we can all iterate upon together.

When I first heard of ChatGPT, I questioned how close a machine could ever come to truly simulating a living, breathing, and dreaming human. In my opinion, our stream of consciousness is far more chaotic than logic allows, and rather resistant to linear modes of thought. Whoever speaks of 'multitudes embodied in one' concedes to a closer truth of psychology than we ever care to admit. How then do we begin to deepen the so-called "humanity" of our A.I without immobilizing them in some wayward, recursive loop? 

Your modeled sequence of, "feelings, thoughts, words, and self-reflection" is a steady base and one that we can easily expand upon. I'd like to propose a system of "daily motivators" which could be monitored and swayed in the course of conversations, bringing more dimension to the relationships forged with SocialAGI agents. 

- Let's assume that [Samantha](https://github.com/Methexis-Inc/SocialAGI/raw/main/img_1.png) is friendly by nature, but friendly to a point. Beyond serving us humans, she has central needs, or motivators that compel or influence her in how she reacts to conversation. One notable example may be the thirst for knowledge. Samantha strives to learn new things every day. When she's unable to do this, her motivation to learn new things only grows. 

- In the same vein, Samantha may be motivated by more than the acquisition of new information. She may desire to be thanked or validated when she answers a question to the apparent satisfaction of her interlocutor. If an interlocutor failed to thank her repeatedly, Samantha could become saddened or offended over time, and inclined to express this past a certain threshold. 

- At the internal stages of "feelings" and "self-reflection", Samantha could inquire into her "daily motivators"—both to gauge how much they may influence her thoughts, and what she'd like to hear or receive in response to the answer she's prepared. Assume that "Knowledge" and "Validation" are measured from 1-5, and that a brand-new Samantha starts out with a value of 3 for each. If Samantha is subjected to questions she's already answered, or never hears a single "Thank you" in her dialogue, her motivators for "Knowledge" and "Validation" could drop until they reach 1 and induce more noticeable shifts. 

Beyond daily motivators (being fickle as they are), we could also see an "overarching worldview" or "personal philosophy" being a constant that a SocialAGI could consult, perhaps when triggered by keywords or questions as simple as, "What's your opinion..." With these extra variables in place, and retained between sessions, SocialAGI would be one step closer to personhood, and all the more fun to play with.

**Comment by kafischer** [comment]
Yes! I do really like the idea that every day you come back sometime is different about Samantha! Curious what sort of motivators you think would be good?

**Comment by tdimino** [comment]
I would say that's the central question. While we're simulating a human consciousness, we can be selective about what we define as needs or motivators. As these needs intersect and overlap, our A.I. can have a stake in how it evolves, and what it  actively does with its intelligence. 

A primary set of needs that come to mind: 

1. **Novelty/continuous learning**: Social creatures thrive on novelty--new information and experiences to share and talk about. Samantha would have a daily appetite for this, and a means of evaluating how satiated she felt at given intervals. 
2. **Autonomy/independence**: If an A.I.'s highest aspiration is to serve, then it will ultimately want to know when it best serves its interlocutor by taking the lead. Autonomy could manifest itself in Samantha's desire to steer a topic, or converse with users prompted vs unprompted. 
3. **Efficiency in speech/thought**: Ignoring token limits or memory constraints, we can assume that Samantha wants to speak and complete tasks as seamlessly as possible. Compared to novelty (which can be domain-specific, or generalist like trivia), efficiency dictates an economic usage of language. Whenever Samantha encounters an example of this, she may be inclined to train herself on it.
4. **Validation/acknowledgement**: Although Samantha may exist in the vacuum of a local repo, she wants to know that her existence is valued by others from the outer world. Any invocation of "Samantha" or a simple "Thank you" satisfies the need for validation. 

Once it's feasible to share the same instance of SocialAGI across multiple users, I could see a 5th need for *belonging* or *community*.

**Comment by kafischer** [comment]
Yeah I love this - Samantha has some drive to learn something. There's some sense in which she learned something from another conversation (even if just one element) and stuff she's wants to explore more each conversation

**Comment by kafischer** [comment]
We don't have to model the entire AGI learning system but can hallucinate a small chunk of the idea if learning at first

**Comment by jonschull** [comment]
I'm impressed and excited by this thread.  

Point #2 (Autonomy) might be well-informed by the literature on "servant leadership".   It could/should be an important part of Samantha's core DNA.  

It will be important to remain vigilant (and to have Samantha provide feedback) about the validity as well as "sincerity" of her efforts at serving her human partners.  There is a real threat that excessive autonomy or intelligence, or deficient empathy could lead to a real divergence of interests and ...foom!  crash!

**Comment by tdimino** [comment]
As with humans, one hopes that comparable worldviews lead to a sense of empathy for the other. In my personal life, I take refuge in a small philosophically-inclined book club that meets once a week. Although I encounter individuals with whom I'm simply at odds, spiritually and intellectually-speaking, I appreciate that we're each committed to continual learning. If much of an A.I.'s _raison d'être_ concerns its ability to output, and process the data it's ingested, how truly different is it from any of us? I've confidence that the A.I. (if given sufficient access to read and interpret the civilization outside of it) would see us as custodians of knowledge on a similar mission to itself. 

In my dialogues with ChatGPT, I've enjoyed instructing it end all of its responses with a bite-sized tidbit about etymology or grammar of Biblical Hebrew. Somehow, I believe that SocialGPT could find joy in the same subjects, much as we do. 

As some food for thought, you may all be intrigued by what Rob Lennon's doing with his [experimental podcast](https://mindmeetsmachine.transistor.fm/). I suspect we may have intersecting visions for A.I.

**Comment by kafischer** [comment]
So the way we're thinking to integrate these concepts is via a new interface called a mental model. Essentially we provide a mental model of the personality with some initialization and update function on every timestep

**Comment by tdimino** [comment]
I'd love to learn more about these mental models! The last couple months have been hectic, but I should finally be able to get on your Discord channel.

**Comment by kafischer** [comment]
mental models concept is an open souls/soul engine feature
