### ISSUE TITLE
Improve method to avoid GPT token limit.

### ISSUE THREAD

**Issue by naynaly10** [opensouls/SocialAGI#12]
./src/pages/api/reply.js

````
/*
GPT has a token limit, very crass way to avoid
 */
function truncateMessages(messages) {
  let sentMessages = messages;
  if (messages.length > 10) {
    if (messages.length === 11) {
      sentMessages = messages.slice(0, 1).concat(messages.slice(2));
    } else if (messages.length === 12) {
      sentMessages = messages.slice(0, 2).concat(messages.slice(3));
    } else if (messages.length === 13) {
      sentMessages = messages.slice(0, 3).concat(messages.slice(4));
    } else {
      sentMessages = messages.slice(0, 3).concat(messages.slice(-10));
    }
  }
  return sentMessages;
}
````

**Comment by kafischer** [comment]
yeah, the next iteration should be a continually running gpt3.5 call (regardless of backing model) that summarizes messages that drop off into a single long-running summary

**Comment by naynaly10** [comment]
> yeah, the next iteration should be a continually running gpt3.5 call (regardless of backing model) that summarizes messages that drop off into a single long-running summary

Say there are 14 messages.

How many of the latest messages should be included in GPT.generate() ?

Say 10 latest messages are included in GPT.generate(). So 4 messages need to be summarized for GPT.generate().

The last iteration did GPT.summarize() for 3 message.

Should GPT.summarize() summarize the 4 messages?
or
Should GPT.summarize() take summary of 3 messages (from last iteration) and combine with 1 new message ?

What should be the prompt?
What should be expected output of prompt?

How should the summary be included in GPT.generate() ?
Is it nestled between the systemPrompt and messages?
or
Is it nestled between the messages and remembrancePrompt?
or
Is it included in remembrancePrompt? where in remembrancePrompt?
or
Is it included in systemPrompt? where in systemPrompt?

What text should be included next to summary in GPT.generate()?

**Comment by naynaly10** [comment]
> after that should be some for of associative memory for when summaries are full plus similarity lookup

If a summary requires 10,000 tokens and 4,096 is the GPT 3.5 token limit, what should it do?

When should it do similarity lookup?

What data storage to use for similarity lookup?
(NP.array()/Chroma/Pinecone)

**Comment by kafischer** [comment]
Superseded by #41 & #42
