### ISSUE TITLE
Return type inference problem with experimentalStreamingNext

### ISSUE THREAD

**Issue by dooart** [opensouls/SocialAGI#120]
The wrong return type is inferred when running experimentalStreamingNext with a cognitive function that has a declared process function.

It's easier to explain with an example:

```typescript
const { nextStep, stream } = await lastStep.experimentalStreamingNext(
  externalDialog(`greets the user`)
);

let streamed = "";
for await (const chunk of stream) {
  process.stdout.write(chunk);
  streamed += chunk;
}

const greet1 = await nextStep;
 // this won't work because the return type is a tuple containing step and stream
console.log(greet1.value);

const [greet2, _stream] = (await nextStep) as unknown as [CortexStep<string>, AsyncIterable<string>];
 // this will work
console.log(greet2.value);
```

I'm actually confused as to why the stream is [returned from the promise](https://github.com/opensouls/SocialAGI/blob/1b9cb7db3be09650f2625bd949d0a24bb84743fa/core/src/next/CortexStep.ts#L290) along with the step, considering it is already returned in the initial call to `experimentalStreamingNext`.

So my suggestion would be returning the step directly (instead of inside a tuple) and adding one more test case to cover this scenario (the current one [is using `instruction`](https://github.com/opensouls/SocialAGI/blob/1b9cb7db3be09650f2625bd949d0a24bb84743fa/core/tests/next/CortexStep.spec.ts#L174) which does not have a process function).

I'd be happy submitting a PR if you agree with my fix suggestion. The only problem is that even though the function is flagged as experimental, it could break someone's code.

**Comment by tobowers** [comment]
Thank you for flagging this. I will look into it today.

**Comment by tobowers** [comment]
Oh yeah that's a bug. The very first pass at this returned the step and stream, but then was changed into returning the step as a promise... but the process section wasn't updated.

Thank you so much for finding this!

**Comment by kafischer** [comment]
Was there a PR that fixed this @tobowers ?

**Comment by tobowers** [comment]
yes! Sorry: this test makes sure this works now: https://github.com/opensouls/SocialAGI/blob/691a7be68f534b061a0f521a5b682b71d4061999/core/tests/cortexStep.spec.ts#L195-L217

Sorry @dooart for not getting back to you right away on this. That's a communication fail on my part.

We've since adjusted the streaming interface here: https://github.com/opensouls/SocialAGI/pull/129 and took it out of experimental status.

**Comment by dooart** [comment]
oh no problem! thank you for looking into this 🎉
