### ISSUE TITLE
ramble action is a lib option passed by default into soul options

### ISSUE THREAD

**Issue by kafischer** [opensouls/SocialAGI#46]

**Comment by tobowers** [comment]
What is this saying? You mean make it turn on/off?

**Comment by kafischer** [comment]
Oh, I was remembering that in Minerva application (and possibly others) rambling isn't desired. So I was imaging that there's like a library of actions that are maintained, e.g. ramble `CoreActions.ramble`. Perhaps ramble isn't even enabled by default at all so no default actions. But it's often canonical to pass in the ramble action?
