### ISSUE TITLE
Discord bot

### ISSUE THREAD

**Issue by kafischer** [opensouls/SocialAGI#6]
V0 to greet in the social AGI Discord

**Comment by Nick-S-Dev** [comment]
Why do you want the discord bot to do. Please describe the commands that the discord bot will recognise. So u can get started!

**Comment by kafischer** [comment]
Hmm, simplest could be to have it in its own channel and respond to every message!

**Comment by Nick-S-Dev** [comment]
So you want to respond to questions like Samantha does? Or should I connected to an api from openai, to respond like a chatbot?

**Comment by kafischer** [comment]
I was imagining a v0 like basically the Samantha chat that currently exists identically but in a Discord channel where she responds to every message - just to get started. Could iterate from there!

**Comment by Nick-S-Dev** [comment]
Ok I will get into it tomorrow😳

**Comment by Nick-S-Dev** [comment]
Question: How can I get access to the api?

`const prompt = interaction.options.getString('question');
           


      
      /*
      Samantha's thoughts are read as a ReadableStream from the OAI endpoint. The stream is then parsed as the thoughts
      come in to remove latency.
       */
        const response = await fetch(`/api/reply`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            messages: prompt,
          }),
        });
        
        console.log(response);
      }`
      
      That's some of the code. I'm trying to send my prompt to Samantha's API so I can get a response. But I get this error:
      
`Failed to parse URL from /api/reply`.

Can you please help me?

**Comment by kafischer** [comment]
Hmm, this makes sense. 

PR #15 is adding a new client API that will be easier to use. Planning to merge soon then start expanding on that.

**Comment by kafischer** [comment]
Would be awesome to build it off this now

https://www.npmjs.com/package/socialagi

**Comment by Nick-S-Dev** [comment]
That's amazing!!! I'm gonna start build tomorrow😊

**Comment by Nick-S-Dev** [comment]
I'm on an trip rn. I'm gonna start on Monday✈️

**Comment by bkitej-rw** [comment]
Think this is done, no?

**Comment by kafischer** [comment]
@Nick-S-Dev not sure if you saw! There's a whole set of discord bot examples now in https://github.com/opensouls/SocialAGI/tree/main/integrations/discord_bots
